### ISSUE TITLE
Typings issues

### ISSUE THREAD

**Issue by dmytro587** [PeculiarVentures/peculiar-react-components#122]
I'm got a several warnings during passing unit tests on the Hancock.

1. Tooltip. Need to mark children prop as optional since we get warning if pass null or undefined.
It get rid of us from the `Failed prop type: The prop 'content' is marked as required in 'Tooltip', but its value is 'null'` warnings.

2. TooltipPopper. Need to mark children prop as optional, it get rid of us from the `Failed prop type: The prop 'children' is marked as required in 'TooltipPopper', but its value is 'null'` warnings.

3. Typography. Need to mark children prop as optional, it get rid of us from the `Failed prop type: The prop 'children' is marked as required in 'Typography', but its value is 'undefined'` warnings.

4. Tooltip & TooltipPopper. I got `Failed prop type: Invalid prop 'usePortal' supplied to 'Tooltip'` and `Failed prop type: Invalid prop 'usePortal' supplied to 'TooltipPopper'` warnings, but to the prop was passed a correct value. I have a guess about the wrong type definition of usePrortal [here](https://github.com/PeculiarVentures/peculiar-react-components/blob/6ce897913606138d835e132272268f7409003ded/packages/components/src/components/tooltip/tooltip_popper.jsx#L231) and [here](https://github.com/PeculiarVentures/peculiar-react-components/blob/6ce897913606138d835e132272268f7409003ded/packages/components/src/components/tooltip/tooltip.jsx#L135), the `usePortal: PropTypes.oneOfType([PropTypes.bool, HTMLElementType])` definition according to the [documentation](https://reactjs.org/docs/typechecking-with-proptypes.html) fixed warnings for me.

**Comment by donskov** [comment]
Should be fixed in `lib-react-components@3.1.5`. Please try.

**Comment by dmytro587** [comment]
> Should be fixed in `lib-react-components@3.1.5`. Please try.

You probably accidentally close this issue instead of #124 because in new version fixed bug described on #124

**Comment by donskov** [comment]
Yes. My mistake. Reopened.

**Comment by donskov** [comment]
@dmytro587 Could you provide an example of using? I do not understand a little, for example, why should we render the Typography without content.

**Comment by dmytro587** [comment]
> @dmytro587 Could you provide an example of using? I do not understand a little, for example, why should we render the Typography without content.

1. Typography. I don't see the point about require `children` prop since:
1.1. `null` and `undefined` is valid values for the render
1.2. we don't handle rendering if `children` is falsy value, we still render `children` whatever it is, so at the moment we get a warning on an empty space. I've done a little research on some other libraries and they don't give warnings if pass falsy values to them, and just display nothing. For example https://codesandbox.io/s/pjll5x?file=/demo.tsx Ant Design has Typography with margins too.
2. Tooltip and TooltipPopper. We have some places on the Hancock where content prop could be falsy, and again, pushing back from other ui components libs - when content for tooltips is empty he just not displayed.

**Comment by donskov** [comment]
1. I will make the changes, but I still don't understand why we need empty text. We don't use any margin there.

**Comment by donskov** [comment]
```
Successfully published:
 - lib-react-components@3.1.6
```
