### ISSUE TITLE
Popper optional modifyers

### ISSUE THREAD

**Issue by SilverTracer** [PeculiarVentures/peculiar-react-components#68]
There's certain scenarios of using `TooltipPopper` component, where we can receive further tooltip behaviour:
Initial state - 
<img width="333" alt="Screenshot 2020-04-06 at 11 13 06" src="https://user-images.githubusercontent.com/25584760/78537219-cb520900-77f7-11ea-8ba9-7b34dae448ff.png">
Flipper state - 
<img width="333" alt="Screenshot 2020-04-06 at 11 13 15" src="https://user-images.githubusercontent.com/25584760/78537184-bd9c8380-77f7-11ea-8cdb-db7f11e48e88.png">
Breaking (sticky) state - 
<img width="333" alt="Screenshot 2020-04-06 at 11 13 18" src="https://user-images.githubusercontent.com/25584760/78537156-b4131b80-77f7-11ea-8a5c-6f6e25a5c26a.png">

I found following [issue](https://github.com/popperjs/popper-core/issues/560) on `popper.js` repository with explanation of this case.
To have ability to fix it, I propose to add optional `modifyers` property into `TooltipPopper` interface and merge it with [initial](https://github.com/PeculiarVentures/react-components/blob/0.3.x/lib/components/tooltip/tooltip_popper.jsx#L129) `modifyers`.
This won't break any of current use-cases of this components and add enough flexibility in usage in future.

**Comment by donskov** [comment]
@SilverTracer Can we close it?

**Comment by SilverTracer** [comment]
> @SilverTracer Can we close it?

Yes, this issue was resolved in linked PR. Sorry for abandoning it.
