### ISSUE TITLE
Add masks for phone num

### ISSUE THREAD

**Issue by MarikTar** [PeculiarVentures/peculiar-react-components#84]
Should we use masks for phone num?
![image](https://user-images.githubusercontent.com/39085824/77420332-816a2b80-6dd2-11ea-9e41-994f91657f94.png)
Sort of:
![image](https://user-images.githubusercontent.com/39085824/77420427-aeb6d980-6dd2-11ea-9f94-324c899ba83b.png)

After resolved, implementation to [#3870](https://github.com/PeculiarVentures/hancock-app/issues/3870)

**Comment by donskov** [comment]
**Requirements**
1. Help the user enter his phone number in the field using a mask.

**What need to do**
1. Speak about the phone field implementation with @alexgbv.
2. Add a support phone field to our components library.
3. Test and publish new components version.

**Info for discussion**
1. each country has a specific phone format and a different prefix and we need to handle it and support it.
```
// US
input: +112234343344
national: (223) 434-3344
international: +1 223 434 3344

// UA
input: +380662232333
national: 066 223 2333
international: +380 66 223 2333
```
2. maybe implement country code select (see links).
![image](https://user-images.githubusercontent.com/9417251/104314309-ea499e00-54e1-11eb-8c3f-4fde8559a1db.png)

**Links**
1. Implementation 1 - https://bl00mber.github.io/react-phone-input-2-css.html
2. Implementation 2 - https://catamphetamine.gitlab.io/react-phone-number-input/

**Comment by donskov** [comment]
@alexgbv Prepared mockup:
![image](https://user-images.githubusercontent.com/9417251/104586088-aa172680-566d-11eb-8944-064a7b5904c0.png)

The solution approved by the team and ready for implementation in the components library.

**Comment by alexgbv** [comment]
![image](https://user-images.githubusercontent.com/39085824/104627248-75bc5e00-569f-11eb-912b-4af22351136e.png)
https://www.figma.com/file/MJze0qkQ2bw0D1oelqqOUK/pv-design-system?node-id=41%3A3

**Comment by donskov** [comment]
I prepared MVP for the phone field component - https://peculiarventures.github.io/peculiar-react-components/demos/phone-field.

@alexgbv @WorldThirteen Please test the component if you have time. Important your feedback about UX.

**Comment by donskov** [comment]
Also, maybe we can move the country code to the button?

![image](https://user-images.githubusercontent.com/9417251/105740983-7330f280-5f42-11eb-8577-421b9d75f609.png)

@alexgbv What do you think?

**Comment by alexgbv** [comment]
@donskov as for me it is better when code and number are not separated.

**Comment by alexgbv** [comment]
> I prepared MVP for the phone field component - https://peculiarventures.github.io/peculiar-react-components/demos/phone-field.
> 
> @alexgbv @WorldThirteen Please test the component if you have time. Important your feedback about UX.

I lean towards grey colored codes vs in a "()". The rest looks good at all.  
![image](https://user-images.githubusercontent.com/39085824/105752812-6ddaa480-5f50-11eb-939c-76354f11bdf9.png)

**Comment by donskov** [comment]
Styles for country code updated:

![image](https://user-images.githubusercontent.com/9417251/105911706-1fea9d00-6033-11eb-9443-c65a938570e7.png)

Link: https://peculiarventures.github.io/peculiar-react-components/demos/phone-field

**Comment by donskov** [comment]
@alexgbv What you think about using emoji flags instead of SVG? This will help to increase our components library by ~40kb.

![image](https://user-images.githubusercontent.com/9417251/106471435-49c81780-64aa-11eb-89d3-6bda6203ac72.png)

**Comment by alexgbv** [comment]
If it will works correctly on all of platforms and help to optimize lib - l do not mind.

**Comment by donskov** [comment]
> @alexgbv What you think about using emoji flags instead of SVG? This will help to increase our components library by ~40kb.
> 
> ![image](https://user-images.githubusercontent.com/9417251/106471435-49c81780-64aa-11eb-89d3-6bda6203ac72.png)

It doesn't work on Windows (.

**Comment by donskov** [comment]
Phone field added to `2.1.0` version and published.
