### ISSUE TITLE
Replace arrow icon control. 

### ISSUE THREAD

**Issue by alexgbv** [PeculiarVentures/peculiar-react-components#90]
I have replaced this element, 'cause old one wasn't clear enough. Please apply new one.

![image](https://user-images.githubusercontent.com/39085824/105036037-9819f700-5a64-11eb-88e5-0998736479be.png)
![image](https://user-images.githubusercontent.com/39085824/105036060-a0723200-5a64-11eb-9994-f7093b114b8a.png)
https://www.figma.com/file/MJze0qkQ2bw0D1oelqqOUK/pv-design-system?node-id=127%3A30

**Comment by donskov** [comment]
@alexgbv Ok

**Comment by donskov** [comment]
@alexgbv Replaced. Result (I will change color styles next releases):

![image](https://user-images.githubusercontent.com/9417251/105680631-acdd0b80-5ef8-11eb-861f-6e219c0ef1e6.png)
