### ISSUE TITLE
Select component bug with keyboard navigation

### ISSUE THREAD

**Issue by apilguk** [PeculiarVentures/peculiar-react-components#94]
![image](https://user-images.githubusercontent.com/5960711/106368070-94814c80-634f-11eb-94b6-673e3aa48d02.png)
by clicking on M focus goes to Venus selecting instead of Mercury as expected

**Comment by donskov** [comment]
Fixed on `2.1.1` and published. 
@apilguk  Please check..

**Comment by apilguk** [comment]
Now it works correct for me, thank you
